export const particleNetworkConfig = {
  particleNetwork: {
    reducedMotionQuery: "(prefers-reduced-motion: reduce)",
    density: {
      baseParticles: 0.00012,
      baseDust: 0.00008,
      minParticles: 70,
      maxParticles: 165,
      reducedMotionParticleFactor: 0.42,
      reducedMotionMinParticles: 30,
      reducedMotionDustFactor: 0.35,
      reducedMotionMinDust: 12,
      minDust: 28,
    },
    links: {
      baseDistance: 118,
      pointerDistance: 170,
    },
    pointer: {
      radius: 190,
      spawnRadius: 130,
      strength: 140,
    },
    motion: {
      maxSpeed: 34,
      randomDrift: 0.75,
      velocityDamping: 0.996,
      respawnRatePerSecond: 0.03,
      lifetimeMin: 14,
      lifetimeMax: 30,
      particleWrapMargin: 44,
      dustWrapMargin: 26,
    },
    rendering: {
      maxDevicePixelRatio: 1.75,
      targetFps: 50,
      defaultColors: {
        pointRgb: "245,245,245",
        linkRgb: "245,245,245",
        dustRgb: "255,255,255",
      },
    },
    spawning: {
      clusterCenterCountMin: 3,
      clusterCenterCountMax: 6,
      nearPointerSpawnChance: 0.58,
      clusteredSpawnChance: 0.3,
      clusterSigmaFactor: 0.18,
      speedMin: 6,
      speedMax: 18,
      radiusMin: 1.05,
      radiusMax: 2.35,
      initialAgeFactorMax: 0.32,
    },
    dust: {
      speedMin: 2,
      speedMax: 6,
      radiusMin: 0.5,
      radiusMax: 1.25,
      alphaMin: 0.08,
      alphaMax: 0.34,
    },
  },
} as const;
